export const CATEGORY_ICON_MAP: Record<string, string> = {
  smartphones:          'smartphone',
  phones:               'smartphone',
  mobile:               'smartphone',
  laptop:               'laptop',
  laptops:              'laptop',
  computer:             'computer',
  computers:            'computer',
  desktop:              'desktop_windows',
  tablet:               'tablet_android',
  tablets:              'tablet_android',
  headphone:            'headphones',
  headphones:           'headphones',
  audio:                'headphones',
  kulaklik:             'headphones',
  kulakliklar:          'headphones',
  camera:               'camera_alt',
  cameras:              'camera_alt',
  tv:                   'tv',
  monitor:              'monitor',
  monitors:             'monitor',
  gaming:               'sports_esports',
  console:              'sports_esports',
  consoles:             'sports_esports',
  keyboard:             'keyboard',
  mouse:                'mouse',
  storage:              'database',
  ssd:                  'database',
  hdd:                  'database',
  memory:               'memory',
  ram:                  'memory',
  processor:            'memory',
  processors:           'memory',
  cpu:                  'memory',
  gpu:                  'monitor_heart',
  graphics:             'monitor_heart',
  accessory:            'cable',
  accessories:          'cable',
  'mobile-accessories': 'cable',
  cable:                'cable',
  charger:              'bolt',
  power:                'bolt',
  battery:              'battery_charging_full',
  speaker:              'speaker',
  speakers:             'speaker',
  wearable:             'watch',
  wearables:            'watch',
  watch:                'watch',
  smartwatch:           'watch',
  printer:              'print',
  printers:             'print',
  network:              'router',
  router:               'router',
  security:             'shield',
  smart:                'home',
  smarthome:            'home',
}

/** All unique icon values available for selection, with display labels */
export const AVAILABLE_ICONS: { icon: string; label: string }[] = [
  { icon: 'smartphone',           label: 'Smartphone' },
  { icon: 'laptop',               label: 'Laptop' },
  { icon: 'computer',             label: 'Computer' },
  { icon: 'desktop_windows',      label: 'Desktop' },
  { icon: 'tablet_android',       label: 'Tablet' },
  { icon: 'headphones',           label: 'Headphones' },
  { icon: 'camera_alt',           label: 'Camera' },
  { icon: 'tv',                   label: 'TV' },
  { icon: 'monitor',              label: 'Monitor' },
  { icon: 'sports_esports',       label: 'Gaming' },
  { icon: 'keyboard',             label: 'Keyboard' },
  { icon: 'mouse',                label: 'Mouse' },
  { icon: 'database',             label: 'Storage' },
  { icon: 'memory',               label: 'Memory / CPU' },
  { icon: 'monitor_heart',        label: 'GPU' },
  { icon: 'cable',                label: 'Accessories' },
  { icon: 'bolt',                 label: 'Charger' },
  { icon: 'battery_charging_full',label: 'Battery' },
  { icon: 'speaker',              label: 'Speaker' },
  { icon: 'watch',                label: 'Wearable' },
  { icon: 'print',                label: 'Printer' },
  { icon: 'router',               label: 'Network' },
  { icon: 'shield',               label: 'Security' },
  { icon: 'home',                 label: 'Smart Home' },
  { icon: 'inventory_2',          label: 'General' },
]

export function getCategoryIcon(id: string, storedIcon?: string | null): string {
  if (storedIcon) return storedIcon
  const lower = id.toLowerCase()
  if (CATEGORY_ICON_MAP[lower]) return CATEGORY_ICON_MAP[lower]
  for (const [key, icon] of Object.entries(CATEGORY_ICON_MAP)) {
    if (lower.includes(key) || key.includes(lower)) return icon
  }
  return 'inventory_2'
}